import React from 'react';

import { fontBody, fontDisplay } from '@/lib/fonts';
import { cn } from '@/utils';
import { TailwindIndicator } from '@/components/ui';

import '@/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps): React.JSX.Element => {
  return (
    <html lang="en">
      <body
        className={cn(fontBody.variable, fontDisplay.variable, 'font-body')}
      >
        {children}

        <TailwindIndicator />
      </body>
    </html>
  );
};

export default RootLayout;
